#!/bin/sh
#
# Uses hawkBit MGMT REST API to enable target security token authentication and
# to create a target with a defined security token:
#
# [{
#   "controllerId":"test-controller",
#   "name":"test-target",
#   "description":"none",
#   "securityToken":"bhVahL1Il1shie2aj2poojeChee6ahShu"
# }]'

HAWKBIT_SERVER="localhost:8080"
HAWKBIT_SERVER_LOGIN="admin:admin"

curl "http://${HAWKBIT_SERVER}/rest/v1/system/configs/authentication.targettoken.enabled" \
	-u ${HAWKBIT_SERVER_LOGIN} \
	-X PUT \
	-H "Content-Type: application/json;charset=UTF-8" -i \
	-d '{"value" : true}'

curl "http://${HAWKBIT_SERVER}/rest/v1/targets" \
	-u ${HAWKBIT_SERVER_LOGIN} \
	-X POST \
	-H "Content-Type: application/json;charset=UTF-8" -i \
	-d '[{"controllerId":"test-controller", "name":"test-target", "description":"none", "securityToken":"bhVahL1Il1shie2aj2poojeChee6ahShu"}]'
