#!/bin/sh
# Author: Lasse K. Mikkelsen
#
# Create target device in hawkBit
#

HAWKBIT_SERVER="10.10.0.254:8080"

ADMIN_USER=admin
ADMIN_PWD=admin
CONTROLLER_ID="test-target"
AUTH_TOKEN="cb115a721af28f781b493fa467819ef5"
TARGET_NAME="test device"
TARGET_DESRIPTION=""

curl -u "$ADMIN_USER:$ADMIN_PWD" "http://$HAWKBIT_SERVER/rest/v1/targets" -i -X POST -H 'Content-Type: application/json;charset=UTF-8' -d "[ { \"securityToken\" : \"$AUTH_TOKEN\", \"controllerId\" : \"$CONTROLLER_ID\", \"name\" : \"$TARGET_NAME\", \"description\" : \"$TARGET_DESCRIPTION\" } ]"
